language: objective-c
osx_image: xcode11.2

env:
  matrix:
      - DESTINATION="OS=10.0,name=iPhone 7 Plus"
      - DESTINATION="platform=iOS Simulator,name=iPhone X"

before_install:
  - gem install cocoapods
  - carthage bootstrap --platform ios

install:
  - gem install xcpretty

script:
  - rake build:ios DESTINATION='OS=10.0,name=iPhone 6s'
  - rake build:ios DESTINATION='platform=iOS Simulator,name=iPhone 7 Plus'
  - pod lib lint --quick
